version: 2
updates:
  - package-ecosystem: "github-actions" # Replace with your package ecosystem (e.g., "npm", "pip", "docker", "maven", "bundler", etc.)
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"